### PR TITLE
bug fixes and enhancements

### PR DESCRIPTION
**Pull request by mamahfouz**
- modifications to the subscription API to record the exchange timestamp in the published market data message

### CODE REVIEW

**Comment by mamahfouz** [comment]
> Actually Mahmoud can you change the `log_print(f'string with var: {var}')` to format `log_print('string with var: {}', var)`

Where did you see that in the code? I just had a look again at my PR and I couldn't see where I did that!

**Comment by ddervs** [comment]
It's in `POVExecutionAgent.py`

**Comment by davebyrd** [comment]
This looks good once the change Danial requested is made.  f-strings should not be used with log_print, as they defeat its purpose.

**Comment by ddervs** [comment]
Mahmoud can you rebase in the changes to agent custom state (PR #9 ) from development before merging this in?

**Pull request merged**
