### PR TITLE
bug fixes for execution agent

### PR DESCRIPTION
**Pull request by mamahfouz**
bug fixes for execution agent

### CODE REVIEW

**Review by ddervs — APPROVED** [review]
Looks good to me!

**Comment by selimamrouni** [comment]
Just to understand, what this fix?

**Comment by mamahfouz** [comment]
There are two changes here (1) adding the log_to_file param for base trading agents + Noise and Value agents to allow for not logging the bz2 files by default and (2) execution agents weren't working out of the box so this has been fixed now

**Review by selimamrouni — APPROVED** [review]
Looks good to me.

**Review by davebyrd — COMMENTED** [review]
It appears we already had log_to_file defaulted to True in the base Agent, and this change cascades it up through financial and trading agent, and adds it specifically to the noise and value agent.  Is the idea that, if and as needed to turn off logging, others can add it to additional agents later?

**Comment by mamahfouz** [comment]
the idea is to allow for disabling logging for certain agents and keep the logs for other agents if that makes sense

**Review by davebyrd — APPROVED** [review]

**Pull request merged**
